language: node_js
node_js: lts/*
os: osx
osx_image: xcode10.2
before_install:
- openssl aes-256-cbc -K $encrypted_f93ab045d251_key -iv $encrypted_f93ab045d251_iv
  -in .travis/deploy-key.enc -out .travis/deploy-key -d
before_script:
  - bin/travis-update-submodule
script:
  - npm run build
after_success:
  - bin/travis-push-submodule-update
