name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: git submodule update --init
      - run: npm install
      - run: npm run build
      - run: bundle install
      - run: |
          echo $CERTIFICATES | base64 -D -o Certificates.p12
          sudo -E security import ./Certificates.p12 -P $P12_PASSWORD
        env:
          CERTIFICATES: ${{ secrets.CERTIFICATES }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
      - run: |
          security list-keychains
          security find-identity -v -p codesigning
      - run: |
          bundle exec fastlane run setup_ci force:true
          bundle exec fastlane set_team
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
      - run: |
          bundle exec fastlane release
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
